import { getServerSession } from "next-auth";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { authOptions } from "./api/auth/[...nextauth]/options";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "campus-log",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
<<<<<<< HEAD
  const session = await getServerSession(authOptions); // Make sure to pass authOptions
  console.log({ session }); // This should log the session with all the necessary fields

  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <nav>
            {session?.user ? (
              <>
                <span>Username: {session.user.username}</span>
                <span>Department: {session.user.department}</span>
                <span>Email: {session.user.email}</span>
                <span>Logout</span>
              </>
            ) : (
              <span>Login</span>
            )}
          </nav>
          {children}
        </body>
      </AuthProvider>
=======
  return (
    <html lang="en">

      <body className={inter.className}>{children}</body>
>>>>>>> develop
    </html>
  );
}
