// import { getServerSession } from "next-auth";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import AuthProvider from "@/context/AuthProvider";
// import { authOptions } from "./api/auth/[...nextauth]/options";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "campus-log",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const session = await getServerSession(authOptions); // Make sure to pass authOptions
//   console.log({ session }); // This should log the session with all the necessary fields

//   return (
//     <html lang="en">
//       <AuthProvider>
//         <body className={inter.className}>
//           {/* <nav>
//             {session?.user ? (
//               <>
//                 <span>Username: {session.user.username}</span>
//                 <span>Department: {session.user.department}</span>
//                 <span>Email: {session.user.email}</span>
//                 <span>Logout</span>
//               </>
//             ) : (
//               <span>Login</span>
//             )}
//           </nav> */}
//           {children}
//         </body>
//       </AuthProvider>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import { getServerSession } from "next-auth";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const session = await getServerSession()
//   console.log({session})
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <nav >
//           {session && <span>Logout</span> }
//           {!session && <span>Login</span> }
//         </nav>
//         {children}</body>
//     </html>
//   );
// }

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";

// import "./globals.css";
// import Navbar from "./(components)/utils/navbar/Navbar";
// import { SidebarDemo } from "./(components)/utils/sidebar/Sidebar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Navbar/>
//         <SidebarDemo/>
//         {children}
//       </body>
//     </html>
//   );
// // }import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import ClientRootLayout from "../context/current-path-service/CurrentPathService"
// import { Metadata } from "next";
// import { getServerSession } from "next-auth";
// import { authOptions } from "./api/auth/[...nextauth]/options";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const session = await getServerSession(authOptions); // Make sure to pass authOptions
//   console.log({ session });

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <ClientRootLayout>{children}</ClientRootLayout>
//       </body>
//     </html>
//   );
// }


// RootLayout.tsx

// import { Inter } from "next/font/google";
// import "./globals.css";
// import ClientRootLayout from "../context/current-path-service/CurrentPathService";
// import { Metadata } from "next";
// import { getServerSession } from "next-auth";
// import { authOptions } from "./api/auth/[...nextauth]/options";
// import { CollegeProvider } from "@/context/college-name-provider/CollegeNameProvider";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const session = await getServerSession(authOptions); // Get server session
//   console.log({ session });

//   return (
//     <html lang="en">
//       <body className={`${inter.className} bg-white`}>
//         <CollegeProvider>
//           <ClientRootLayout session={session}>{children}</ClientRootLayout>
//         </CollegeProvider>
//       </body>
//     </html>
//   );
// }



import { Inter } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/options";
import { CollegeProvider } from "@/context/college-name-provider/CollegeNameProvider";
import ClientRootLayout from "../context/current-path-service/CurrentPathService";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <body className={`${inter.className} bg-white`}>
      <CollegeProvider>
        <ClientRootLayout session={session}>
          {children}
        </ClientRootLayout>
      </CollegeProvider>
    </body>
  );
}
